const merchantList = [
    ["Tesco Stores"],
    ["Asda"],
    ["Co-operative Food"],
    ["Morrisons"],
    ["Sainsbury's", "Sainsburys"],
    ["McDonald's"],
    ["Aldi"],
    ["Amazon", "Amzn"],
    ["Apple"],
    ["Lidl"],
    ["Boots"],
    ["Shell"],
    ["Primark"],
    ["Greggs"],
    ["HOME BARGAINS"],
    ["Costa Coffee"],
    ["Netflix"],
    ["Waitrose"],
    ["Uber Eats", "uber *eats",],
    ["Uber", "Uber *trip", "uberbv", "uber trip","crv*uber", "paypal *uber", "sp * uber"],
    ["Iceland Foods"],
    ["Just Eat"],
    ["Marks & Spencer", "M&S"],
    ["Poundland"],
    ["B&M Stores"],
    ["JD Wetherspoon"],
    ["Wilkinsons"],
    ["B&Q"],
    ["BP"],
    ["One Stop"],
    ["Next"],
    ["KFC"],
    ["Argos"],
    ["Superdrug"],
    ["Starbucks"],
    ["Subway"],
    ["TK Maxx"],
    ["Pret A Manger"],
    ["Sports Direct"],
    ["New Look"],
    ["Exxon Mobile UK"],
    ["McColls Convenience"],
    ["Debenhams"],
    ["Pets At Home"],
    ["Spotify"],
    ["Card Factory"],
    ["Now TV"],
    ["TheTrainline.com"],
    ["H & M"],
    ["Utilita"],
    ["John Lewis"],
    ["WH Smith"],
    ["Matalan"],
    ["Caffe Nero"],
    ["The Range"],
    ["Giffgaff.com"],
    ["Nando's"],
    ["Screwfix"],
    ["Savers"],
    ["Homebase"],
    ["Deliveroo"],
    ['Gather and Gather', 'SQ*Gather', 'GATHER &']
  ];
  
  export default merchantList;